[package]
name = "graph-algs"
version = "0.1.0"
authors = ["Max McCarthy <hello@maxmcc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
maplit = "1.0.2"
